# Generated by Django 5.0.1 on 2024-01-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_course_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link_video',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='Фото'),
        ),
    ]
